---
  resources:
    -name: shell-app
    type: git
    source:
      uri: https://github.com/ravis-git/concourse-shell.git

  jobs:
    -name: job-shell-app
      public: true
      plan:
        -get: shell-app
          trigger: true
        -task: shell-execute
          file: shell-app/shell-pipeline.yml
